import { useEffect, useRef, useState, type CSSProperties } from 'react';
import { currentLyric, fetchLyrics, parseLrc, type LyricLine } from './lyrics';
export function LyricsPanel({ identity, title, artist, duration, time, color, seek }: { identity: string; title: string; artist: string; duration?: number; time: number; color: string; seek: (time: number) => void }) {
  const [lines, setLines] = useState<LyricLine[]>([]); const [plain, setPlain] = useState(''); const [message, setMessage] = useState('Finding lyrics...'); const [follow, setFollow] = useState(true); const [source, setSource] = useState('');
  const request = useRef<AbortController | undefined>(undefined);
  const current = currentLyric(lines, time); const body = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const controller = new AbortController(); request.current = controller; setLines([]); setPlain(''); setSource(''); setMessage('Finding lyrics...');
    if (!artist) { setMessage('Add an LRC file to follow this song.'); return () => controller.abort(); }
    void fetchLyrics(title, artist, duration, controller.signal).then(result => { if (controller.signal.aborted) return; setLines(result.lines); setPlain(result.plain); setSource('LRCLIB'); setMessage(result.instrumental ? 'Instrumental · no lyrics' : result.lines.length ? 'Synced lyrics' : result.plain ? 'Lyrics · timing unavailable' : 'No matching lyrics available'); }).catch(() => { if (!controller.signal.aborted) setMessage('No matching lyrics available. You can add an LRC file.'); });
    return () => controller.abort();
  }, [identity, title, artist]);
  useEffect(() => { if (!follow || current < 0 || !body.current) return; const element = body.current.children[current] as HTMLElement | undefined; if (element) body.current.scrollTop = Math.max(0, element.offsetTop - body.current.offsetTop - body.current.clientHeight / 2 + element.clientHeight / 2); }, [current, follow]);
  return <section className="lyrics-panel" aria-label="Song lyrics" style={{ '--song-color': color } as CSSProperties}><div className="lyrics-tools"><span role="status">{message}</span><button aria-pressed={follow} onClick={() => setFollow(value => !value)}>Follow lyrics</button><label className="lyrics-import">Add LRC<input aria-label="Import synced lyrics" type="file" accept=".lrc,text/plain" onChange={event => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 200_000) { setMessage('Choose an LRC file under 200 KB.'); return; } request.current?.abort(); void file.text().then(text => { const parsed = parseLrc(text); if (!parsed.length) throw new Error(); setLines(parsed); setPlain(''); setSource('Your LRC file'); setMessage('Synced lyrics'); }).catch(() => setMessage('This file has no valid timed lyrics.')); event.target.value = ''; }} /></label></div><div className="lyric-lines" ref={body}>{lines.map((line, index) => <button key={`${line.time}-${index}`} className={index === current ? 'lyric-current' : index < current ? 'lyric-past' : ''} aria-current={index === current ? 'true' : undefined} onClick={() => seek(line.time)}>{line.text || '♪'}</button>)}{!lines.length && plain && <p className="plain-lyrics">{plain}</p>}</div>{source && <small>{source === 'LRCLIB' ? <a href="https://lrclib.net" target="_blank" rel="noopener noreferrer">Lyrics: LRCLIB</a> : source} · line-by-line sync</small>}</section>;
}
