import { it, expect } from 'vitest';
import { readTaste, rememberSearch, rememberListen, recommendedTracks, tasteKey, updateTaste, rememberListeningTime } from '../src/renderer/music/listeningTaste';
const storage = () => { const data = new Map<string,string>(); return {getItem:(key:string)=>data.get(key)??null,setItem:(key:string,value:string)=>{data.set(key,value);}}; };
const song = (id:string,artist:string,genre='Pop') => ({id,title:`${artist} - Song ${id}`,user:{name:'Uploader'},genre,duration:180});
it('keeps bounded deduplicated recent queries in latest-first order across reads',()=>{const s=storage();rememberSearch(s,'positions');rememberSearch(s,'Hello');rememberSearch(s,' Positions ');expect(readTaste(s).data.recent).toEqual(['Positions','Hello']);for(let n=0;n<20;n++)rememberSearch(s,`song ${n}`);expect(readTaste(s).data.recent).toHaveLength(12);expect(rememberSearch(s,' ')).toBe(false);});
it('preserves malformed and oversized preferences and blocks every write',()=>{for(const raw of ['{broken','x'.repeat(100001)]){const s=storage();s.setItem(tasteKey,raw);expect(readTaste(s).blocked).toBe(true);expect(rememberSearch(s,'Hello')).toBe(false);expect(s.getItem(tasteKey)).toBe(raw);}});
it('ranks matching artists and genres, excludes current song, alternates, short and duplicates',()=>{const s=storage();rememberListen(s,song('a','Ariana Grande'));const pool=[song('b','Adele','Jazz'),song('c','Ariana Grande'),song('d','Ariana Grande'),song('e','Ariana Grande'),song('f','Bruno Mars'),song('a','Ariana Grande'),{...song('g','Ariana Grande'),title:'Ariana Grande - Song Remix'},{...song('h','Ariana Grande'),duration:20},song('c','Ariana Grande')];expect(recommendedTracks(pool,readTaste(s).data).map(t=>t.id)).toEqual(['c','d','f']);});
it('bounds song-choice history and supports resetting recommendations without deleting searches',()=>{const s=storage();rememberSearch(s,'Hello');for(let n=0;n<100;n++)rememberListen(s,song(`a${n}`,'Adele'));expect(readTaste(s).data.listens).toHaveLength(80);updateTaste(s,v=>({...v,listens:[]}));expect(readTaste(s).data.recent).toEqual(['Hello']);expect(recommendedTracks([song('a','Adele')],readTaste(s).data)).toEqual([]);});
it('handles unavailable storage without breaking music',()=>{const s={getItem:()=>null,setItem:()=>{throw new Error('Quota');}};expect(rememberSearch(s,'Hello')).toBe(false);});

it('weights sustained listening above a brief song choice',()=>{const s=storage();rememberListen(s,song('a','Ariana Grande','Pop'));rememberListen(s,song('b','Adele','Jazz'));rememberListeningTime(s,song('a','Ariana Grande','Pop'));expect(readTaste(s).data.listens.find(item=>item.id==='Audius:a')?.seconds).toBe(30);expect(recommendedTracks([song('c','Adele','Jazz'),song('d','Ariana Grande','Pop')],readTaste(s).data)[0].id).toBe('d');});

it('keeps bounded recently played metadata and preserves older preference records',()=>{const s=storage();s.setItem(tasteKey,JSON.stringify({version:1,recent:['Hello'],listens:[]}));expect(readTaste(s).data.tracks).toEqual([]);for(let n=0;n<30;n++)rememberListen(s,song(`a${n}`,'Adele'));expect(readTaste(s).data.tracks).toHaveLength(24);expect(readTaste(s).data.tracks[0].id).toBe('a29');expect(readTaste(s).data.recent).toEqual(['Hello']);});
