import { chromium, expect } from '@playwright/test';
import { readFileSync, mkdirSync } from 'node:fs';
const browser = await chromium.launch({ channel: 'msedge', headless: true });
mkdirSync('.runtime/jamendo', { recursive: true });
try {
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  const song = { id: 'jm:123', title: 'Night drive', user: { name: 'Independent Artist' }, provider: 'Jamendo', artistId: '4', albumId: '5', albumName: 'Night Album', duration: 180, streamUrl: 'https://prod-1.storage.jamendo.com/?trackid=123&format=mp32', sourceUrl: 'https://www.jamendo.com/track/123', licenseUrl: 'https://creativecommons.org/licenses/by/4.0/' };
  const requests = [];
  await page.route('**/api/jamendo?**', route => { requests.push(new URL(route.request().url())); return route.fulfill({ json: { configured: true, tracks: [song] } }); });
  await page.route('https://api.audius.co/**', route => route.fulfill({ json: { data: [] } }));
  await page.route('https://archive.org/**', route => route.fulfill({ json: { response: { docs: [] } } }));
  await page.route('**/api/ccmixter?**', route => route.fulfill({ json: [] }));
  await page.route('https://api.openverse.org/**', route => route.fulfill({ json: { results: [] } }));
  await page.route('https://prod-1.storage.jamendo.com/**', route => route.fulfill({ contentType: 'audio/mpeg', body: readFileSync('tests/fixtures/original-long-tone.mp3') }));
  await page.goto('http://127.0.0.1:4173/');
  const discovery = page.getByRole('region', { name: 'Jamendo artists and albums' });
  await expect(discovery.locator('.jamendo-card')).toHaveCount(1);
  await discovery.getByRole('button', { name: 'Independent Artist Explore artist' }).click();
  await expect(discovery.locator('.jamendo-card')).toContainText('Night drive');
  expect(requests.some(url => url.searchParams.get('artistId') === '4')).toBe(true);
  await discovery.locator('.jamendo-card').click();
  await expect.poll(() => page.locator('audio').evaluate(audio => audio.currentTime)).toBeGreaterThan(0);
  await discovery.getByRole('button', { name: 'Back to discovery' }).click();
  await discovery.getByRole('button', { name: 'Albums', exact: true }).click();
  await expect(discovery.locator('.jamendo-card')).toContainText('Night Album');
  await discovery.locator('.jamendo-card').click();
  await expect(discovery.locator('.jamendo-card')).toContainText('Night drive');
  await expect.poll(() => requests.some(url => url.searchParams.get('albumId') === '5')).toBe(true);
  await page.getByRole('combobox', { name: 'Search free music' }).fill('Night drive');
  await page.locator('#catalog-search-form').getByRole('button', { name: 'Search', exact: true }).click();
  await expect(page.locator('.catalog-track')).toHaveCount(1);
  await expect(page.locator('.catalog-track')).toContainText('Jamendo');
  await page.keyboard.press('Escape');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await discovery.screenshot({ path: '.runtime/jamendo/phone.png' });
  expect(errors).toEqual([]);
  console.log('PASS: direct Jamendo artist/album filters, main search, actual fixture MP3 playback, phone layout. No public API account used.');
} finally { await browser.close(); }
