import { chromium, expect, _electron as electron } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { preview } from 'vite';
import { createServer } from 'node:http';
import { mkdirSync, mkdtempSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
const output = resolve('.runtime/music'); mkdirSync(output, { recursive: true });
const report = { assertions: [], errors: [] }; const pass = text => { report.assertions.push(text); console.log(`PASS ${text}`); };
const server = await preview({ mode: 'web-preview', preview: { host: '127.0.0.1', port: 0 } });
const fixture = createServer((_request, response) => { response.end('<title>Music site fixture</title><h1>Independent music page</h1>'); });
await new Promise(resolve => fixture.listen(0, '127.0.0.1', resolve));
let browser, app;
try {
  browser = await chromium.launch({ channel: 'msedge', headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 920 } });
  await context.addInitScript(() => { const Native = window.AudioContext; window.__audioContexts = []; window.AudioContext = class extends Native { constructor(...args) { super(...args); window.__audioContexts.push(this); } }; });
  // External link destinations are intercepted; no public artist playback/account requests.
  await context.route(/https:\/\/(tychomusic|bonobomusic|www.nilsfrahm|bandcamp)\.com\//, route => route.fulfill({ contentType: 'text/html', body: '<h1>Artist link fixture</h1>' }));
  const page = await context.newPage(); page.on('pageerror', error => report.errors.push(error.message));
  await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/?design=classic`);
  await expect(page.getByRole('heading', { name: 'A little room for good sounds.' })).toBeVisible();
  expect(await page.evaluate(() => window.__audioContexts.length)).toBe(0);
  await page.screenshot({ path: resolve(output, 'home.png') });
  pass('Classic music layout remains available, with no autoplay.');
  await page.getByRole('button', { name: 'Glow', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Glow', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Play ambient loop' }).first().click();
  await expect(page.getByRole('button', { name: 'Pause ambient loop' }).first()).toBeVisible();
  expect(await page.evaluate(() => window.__audioContexts.at(-1).state)).toBe('running');
  const rotation = await page.locator('.vinyl').evaluate(element => getComputedStyle(element).transform);
  await page.waitForTimeout(120);
  expect(await page.locator('.vinyl').evaluate(element => getComputedStyle(element).transform)).not.toBe(rotation);
  await page.getByRole('button', { name: 'Pause visual motion' }).click();
  await expect.poll(() => page.locator('.vinyl').evaluate(element => getComputedStyle(element).animationPlayState)).toBe('paused');
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  const frozen = await page.locator('.vinyl').evaluate(element => getComputedStyle(element).transform);
  await page.waitForTimeout(120);
  expect(await page.locator('.vinyl').evaluate(element => getComputedStyle(element).transform)).toBe(frozen);
  await page.getByRole('button', { name: 'Pause visual motion' }).click();
  await page.getByRole('slider', { name: 'Volume', exact: true }).fill('0.2');
  await page.getByRole('button', { name: 'Pause ambient loop' }).first().click();
  await expect.poll(() => page.evaluate(() => window.__audioContexts.at(-1).state)).toBe('closed');
  await page.getByRole('button', { name: 'Play ambient loop' }).first().click();
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, value: true }); document.dispatchEvent(new Event('visibilitychange')); });
  await expect.poll(() => page.evaluate(() => window.__audioContexts.at(-1).state)).toBe('closed');
  await page.evaluate(() => { delete document.hidden; });
  pass('Mood selection, real synthesized audio, volume and stop work.');
  await page.getByRole('textbox', { name: 'Companion name' }).fill('Mochi');
  await page.getByRole('combobox', { name: 'Companion temperament' }).selectOption('playful');
  await page.getByRole('button', { name: 'mint companion' }).click();
  await page.getByRole('combobox', { name: 'Companion accessory' }).selectOption('sprout');
  await page.getByRole('button', { name: 'Move Mochi' }).scrollIntoViewIfNeeded();
  const move = page.getByRole('button', { name: 'Move Mochi' });
  for (let i = 0; i < 5; i++) await move.press('Enter');
  await expect(page.locator('.buddy-memory')).toContainText('getting comfortable');
  const old = await page.evaluate(() => JSON.parse(localStorage.getItem('focusspace.music.v1')));
  await move.press('Space'); await move.press('ArrowLeft'); await move.press('Space');
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('focusspace.music.v1')).x)).toBeLessThan(old.x);
  await move.press('Space'); await move.press('ArrowRight'); await move.press('Escape');
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('focusspace.music.v1')));
  await page.reload(); await expect(page.getByRole('button', { name: 'Move Mochi' })).toBeVisible();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('focusspace.music.v1')))).toEqual(saved);
  pass('Companion customization, familiarity and Space/arrow/drop/cancel persist.');
  const buddy = page.getByRole('button', { name: 'Move Mochi' }); const bounds = await buddy.boundingBox();
  await page.mouse.move(bounds.x + 50, bounds.y + 50); await page.mouse.down(); await page.mouse.move(bounds.x + 10, bounds.y + 10, { steps: 12 }); await page.mouse.up();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('focusspace.music.v1')).x)).toBeLessThan(saved.x);
  pass('Pointer dragging saves companion placement.');
  await page.route('https://api.audius.co/v1/tracks/**', route => route.fulfill({ json: { data: [] } }));
  await page.getByRole('button', { name: 'Explore Chill music', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Chill mix', exact: true })).toBeVisible();
  await expect(page.getByRole('combobox', { name: 'Search free music' })).toHaveValue('');
  await page.getByRole('button', { name: 'Close mood mix' }).click();
  pass('Mood exploration opens a separate mix without changing search.');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await expect(page.getByRole('button', { name: 'Pause visual motion' })).toBeDisabled();
  expect(await page.locator('.buddy-shape').evaluate(element => getComputedStyle(element).animationName)).toBe('none');
  for (const viewport of [{ width: 390, height: 844 }, { width: 720, height: 460 }]) {
    await page.setViewportSize(viewport);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.locator('.music-app').evaluate(element => element.scrollTop = 0);
    await page.screenshot({ path: resolve(output, `home-${viewport.width}.png`) });
  }
  const audit = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  report.accessibility = { violations: audit.violations.map(rule => rule.id), incomplete: audit.incomplete.map(rule => rule.id) }; expect(report.accessibility.violations).toEqual([]);
  pass('Responsive music home, reduced motion and automated accessibility pass.');
  await page.evaluate(() => localStorage.setItem('focusspace.music.v1', '{broken')); await page.reload(); await expect(page.getByRole('alert')).toContainText('preserved');
  await page.getByRole('button', { name: 'peach companion' }).click(); expect(await page.evaluate(() => localStorage.getItem('focusspace.music.v1'))).toBe('{broken');
  pass('Malformed music preferences are preserved rather than overwritten.');
  const env = { ...process.env, FOCUSSPACE_DATA_DIR: mkdtempSync(resolve(output, 'desktop-data-')) }; delete env.ELECTRON_RUN_AS_NODE; delete env.FOCUSSPACE_LEGACY;
  app = await electron.launch({ executablePath: resolve('node_modules/electron/dist/electron.exe'), args: [resolve('dist/main/main.cjs')], env });
  const desktop = await app.firstWindow(); await expect(desktop.getByRole('heading', { name: 'For you', exact: true })).toBeVisible();
  await desktop.getByRole('link', { name: 'Moods', exact: true }).click();
  const legacyBefore = await desktop.evaluate(async () => (await window.focusspace.call({ type: 'load' })).data);
  const rejected = await desktop.evaluate(async () => window.focusspace.call({ type: 'browse', url: 'file:///C:/Windows/system.ini' }));
  expect(rejected.ok).toBe(false);
  await desktop.evaluate(async url => window.focusspace.call({ type: 'browse', url }), `http://127.0.0.1:${fixture.address().port}`);
  await expect(desktop.getByRole('button', { name: 'Back to listening' })).toBeVisible();
  const isolated = await app.evaluate(({ BrowserWindow }) => { const view = BrowserWindow.getAllWindows()[0].contentView.children[0]; return { title: view.webContents.getTitle(), preferences: view.webContents.getLastWebPreferences() }; });
  expect(isolated.preferences.sandbox).toBe(true); expect(isolated.preferences.nodeIntegration).toBe(false); expect(isolated.preferences.preload).toBeFalsy();
  await desktop.getByRole('button', { name: 'Back to listening' }).click();
  expect(await desktop.evaluate(async () => (await window.focusspace.call({ type: 'load' })).data)).toEqual(legacyBefore);
  await desktop.locator('.music-extras summary').click();
  await desktop.getByRole('link', { name: 'Previous spaces' }).click();
  await expect(desktop.getByRole('heading', { name: 'A little room for big ideas.' })).toBeVisible();
  await desktop.getByRole('link', { name: 'Listening room', exact: true }).click();
  await expect(desktop.getByRole('heading', { name: 'For you', exact: true })).toBeVisible();
  pass('Native music browsing uses the isolated website view and leaves legacy data unchanged.');
  expect(report.errors).toEqual([]);
} finally {
  if (app) await app.close(); if (browser) await browser.close();
  writeFileSync(resolve(output, 'report.json'), JSON.stringify(report, null, 2));
  await new Promise(resolve => server.httpServer.close(resolve)); await new Promise(resolve => fixture.close(resolve));
}
