import { chromium, expect } from '@playwright/test';
import { readFileSync, mkdirSync } from 'node:fs';
const browser=await chromium.launch({channel:'msedge',headless:true});mkdirSync('.runtime/tuniko',{recursive:true});
try {
 const page=await browser.newPage({viewport:{width:1280,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));let term='';
 await page.route('https://archive.org/**',r=>r.fulfill({json:{response:{docs:[]}}}));await page.route('https://api.openverse.org/**',r=>r.fulfill({json:{results:[]}}));await page.route('**/api/ccmixter?**',r=>r.fulfill({json:[]}));
 await page.route('https://api.audius.co/**',r=>{const url=r.request().url();if(url.includes('/stream?'))return r.fulfill({contentType:'audio/mpeg',body:readFileSync('tests/fixtures/original-long-tone.mp3')});term=new URL(url).searchParams.get('query')||'';return r.fulfill({json:{data:[{id:'blue',title:`Blue sky ${term}`,user:{name:'Fixture'},artwork:{'1000x1000':'https://art.fixture/blue.svg','480x480':'https://art.fixture/low.svg'}},{id:'rose',title:`Rose glow ${term}`,user:{name:'Fixture'},artwork:{'1000x1000':'https://art.fixture/broken.svg','480x480':'https://art.fixture/rose.svg'}}]}});});
 await page.route('https://art.fixture/**',r=>r.request().url().includes('broken')?r.fulfill({status:404}):r.fulfill({contentType:'image/svg+xml',headers:{'access-control-allow-origin':'*'},body:`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="1000"><rect width="1000" height="1000" fill="${r.request().url().includes('blue')?'#5599dd':'#dd5599'}"/></svg>`}));
 await page.goto('http://127.0.0.1:4173/');await expect(page).toHaveTitle('Tuniko');await expect(page.locator('.music-brand')).toContainText('tuniko');await expect(page.getByText('Made for your own rhythm.')).toHaveCount(0);await expect(page.locator('.artist-window')).toHaveCount(0);await expect(page.locator('.mood-card')).toHaveCount(6);
 for(const mood of ['Chill','Happy','Focus','Energy','Romance','Night']) {await page.getByRole('button',{name:`Explore ${mood} music`,exact:true}).click();await expect(page.getByRole('dialog',{name:`${mood} mix`,exact:true})).toBeVisible();await expect(page.getByRole('combobox',{name:'Search free music'})).toHaveValue('');await page.getByRole('button',{name:'Close mood mix'}).click();}
 await page.getByRole('combobox',{name:'Search free music'}).fill('blue');await page.locator('#catalog-search-form').evaluate(form=>form.requestSubmit());await expect(page.locator('.catalog-track')).toHaveCount(2);
 await expect(page.locator('.catalog-track').first().locator('img')).toHaveAttribute('src','https://art.fixture/blue.svg');await expect(page.locator('.catalog-track').nth(1).locator('img')).toHaveAttribute('src','https://art.fixture/rose.svg');await page.getByRole('button',{name:/^Stream Blue sky /}).click();await expect.poll(()=>page.locator('.audio-deck').evaluate(el=>el.style.getPropertyValue('--song-color'))).toBe('rgb(85, 153, 221)');
 await page.getByLabel('Player theme',{exact:true}).selectOption('ocean');expect(await page.locator('.audio-deck').evaluate(el=>el.style.getPropertyValue('--song-color'))).toBe('#91c8c1');await page.getByLabel('Player theme',{exact:true}).selectOption('auto');await page.getByRole('combobox',{name:'Search free music'}).focus();await page.getByRole('button',{name:/^Stream Rose glow /}).click();await expect.poll(()=>page.locator('.audio-deck').evaluate(el=>el.style.getPropertyValue('--song-color'))).toBe('rgb(221, 85, 153)');
 await page.locator('.audio-library').screenshot({path:'.runtime/tuniko/player.png'});await page.locator('.music-discover').screenshot({path:'.runtime/tuniko/moods.png'});await page.setViewportSize({width:390,height:844});await page.locator('.music-discover').scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'.runtime/tuniko/phone.png'});await page.emulateMedia({reducedMotion:'reduce'});expect(await page.locator('.mood-art i').first().evaluate(el=>getComputedStyle(el).animationName)).toBe('none');expect(errors).toEqual([]);console.log('PASS Tuniko branding, six separate mood windows, highest artwork and fallback, artwork/song palettes and override, phone layout/reduced motion');
}finally{await browser.close();}
